[GENERAL]
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[SEARCH]
PROVIDER = "google_custom_search"

[SEARCH.SEARXNG]
API_URL = ""

[SEARCH.GOOGLE_CUSTOM_SEARCH]
API_KEY = ""
CX = ""

[MODELS.OPENAI]
API_KEY = ""

[MODELS.GROQ]
API_KEY = ""

[MODELS.ANTHROPIC]
API_KEY = ""

[MODELS.GEMINI]
API_KEY = ""

[MODELS.CUSTOM_OPENAI]
API_KEY = ""
API_URL = ""
MODEL_NAME = ""

[MODELS.OLLAMA]
API_URL = ""

[MODELS.DEEPSEEK]
API_KEY = ""

[MODELS.AIMLAPI]
API_KEY = ""

[MODELS.LM_STUDIO]
API_URL = ""

[MODELS.LEMONADE]
API_URL = ""
API_KEY = ""

[API_ENDPOINTS]
SEARXNG = ""
