import { UIConfigField } from '@/lib/config/types';

export const priorArtConfigFields: UIConfigField[] = [
  {
    name: 'USPTO ODP API Key',
    key: 'usptoOdpApiKey',
    type: 'password',
    required: true,
    description: 'API key for USPTO Open Data Portal (https://developer.uspto.gov/).',
    placeholder: 'sk-...',
    scope: 'server',
    env: 'USPTO_ODP_API_KEY',
  },
  {
    name: 'USPTO ODP Base URL',
    key: 'usptoOdpBaseUrl',
    type: 'string',
    required: false,
    description: 'Base URL for ODP (defaults to https://api.uspto.gov).',
    default: 'https://api.uspto.gov',
    scope: 'server',
  },
  {
    name: 'USPTO Legacy Base URL',
    key: 'usptoOdpLegacyBaseUrl',
    type: 'string',
    required: false,
    description: 'Legacy host for un-migrated Office Action endpoints.',
    default: 'https://developer.uspto.gov',
    scope: 'server',
  },
  {
    name: 'Use legacy host for Office Actions',
    key: 'oaUseLegacyHost',
    type: 'switch',
    required: false,
    description: 'If true, OA requests go to developer.uspto.gov until ODP completes migration.',
    default: true,
    scope: 'server',
  },
  {
    name: 'GCP Project ID',
    key: 'gcpProjectId',
    type: 'string',
    required: true,
    description: 'Google Cloud project that owns the BigQuery jobs.',
    placeholder: 'my-allodial-project',
    scope: 'server',
    env: 'GCP_PROJECT_ID',
  },
  {
    name: 'GCP Credentials Path',
    key: 'gcpCredentialsPath',
    type: 'string',
    required: false,
    description: 'Path to service account JSON. Leave blank to use Application Default Credentials.',
    placeholder: '/secrets/gcp.json',
    scope: 'server',
    env: 'GOOGLE_APPLICATION_CREDENTIALS',
  },
  {
    name: 'BigQuery Patents Dataset',
    key: 'bigqueryPatentsDataset',
    type: 'string',
    required: false,
    description: 'Fully-qualified table reference for Google Patents Public Data.',
    default: 'patents-public-data.patents.publications',
    scope: 'server',
  },
  {
    name: 'BigQuery Bytes-Billed Cap',
    key: 'bigqueryBytesBilledCap',
    type: 'string',
    required: false,
    description: 'Max bytes billed per BigQuery query (refused via dry-run estimate above this).',
    default: '300000000000',
    scope: 'server',
  },
  {
    name: 'Embedding Model',
    key: 'embeddingModel',
    type: 'string',
    required: false,
    description:
      'Hugging Face model id for local Transformers.js embeddings. BGE-M3 (1024-d) is the default; swap to Xenova/all-MiniLM-L6-v2 (384-d, lower quality) for fast/cheap.',
    default: 'Xenova/bge-m3',
    scope: 'server',
  },
  {
    name: 'Embedding Dimension',
    key: 'embeddingDimension',
    type: 'string',
    required: false,
    description: 'Vector dimension for the chosen embedding model (BGE-M3 = 1024, MiniLM-L6 = 384).',
    default: '1024',
    scope: 'server',
  },
  {
    name: 'Enable Deep Research Reframe',
    key: 'enableDeepResearchReframe',
    type: 'switch',
    required: false,
    description:
      'Run Gemini Deep Research (grounded web search) before USPTO/BigQuery search to disambiguate ambiguous terms and surface non-patent prior art. Adds ~30-90s to each run. Requires GEMINI_API_KEY.',
    default: true,
    scope: 'server',
  },
  {
    name: 'Deep Research Reframe Model',
    key: 'deepResearchReframeModel',
    type: 'string',
    required: false,
    description:
      'Gemini model for the reframe step. gemini-2.5-pro runs a 2-call grounded→structured flow; gemini-3-pro (when available) can do it in one call.',
    default: 'gemini-2.5-pro',
    scope: 'server',
  },
  {
    name: 'CPC Whitelist (BigQuery)',
    key: 'cpcWhitelist',
    type: 'string',
    required: false,
    description:
      'Comma-separated CPC prefixes that BigQuery results must match (hard floor). Default scopes to software + semiconductor + data-center.',
    default: 'G06F,G06N,G06Q,G06T,G06V,H04L,H04W,H01L,G11C,G05B,H03K,G06K',
    scope: 'server',
  },
  {
    name: 'USPC Whitelist (USPTO)',
    key: 'uspcWhitelist',
    type: 'string',
    required: false,
    description:
      'Comma-separated US classification numbers that USPTO ODP results must match (hard floor). Default scopes to software + semiconductor + data-center.',
    default: '706,707,708,709,710,711,712,713,714,716,717,718,719,257,326,327,365',
    scope: 'server',
  },
  {
    name: 'Coverage Threshold',
    key: 'coverageThreshold',
    type: 'string',
    required: false,
    description:
      'Cosine similarity threshold above which a reference is considered to "cover" a technical element. 0.55 for BGE-M3; drop to ~0.45 for MiniLM.',
    default: '0.72',
    scope: 'server',
  },
  {
    name: 'Max Results Per Source',
    key: 'maxResultsPerSource',
    type: 'string',
    required: false,
    description: 'Cap on documents pulled from each source per run.',
    default: '50',
    scope: 'server',
  },
  {
    name: 'Max Documents to Embed',
    key: 'maxDocumentsToEmbed',
    type: 'string',
    required: false,
    description: 'Cap on documents embedded per run (title + abstract + first claim only).',
    default: '200',
    scope: 'server',
  },
  {
    name: 'Top K Final References',
    key: 'topK',
    type: 'string',
    required: false,
    description: 'Number of post-fusion references retained for analysis.',
    default: '20',
    scope: 'server',
  },
  {
    name: 'Request Timeout (seconds)',
    key: 'requestTimeoutSeconds',
    type: 'string',
    required: false,
    description: 'HTTP timeout for ODP requests.',
    default: '30',
    scope: 'server',
  },
  {
    name: 'Workspace Root',
    key: 'workspacePath',
    type: 'string',
    required: false,
    description: 'Directory where per-feature memos and JSON bundles are written.',
    default: 'data/priorart/workspaces',
    scope: 'server',
  },
  {
    name: 'Vector Store Root',
    key: 'vectorStorePath',
    type: 'string',
    required: false,
    description: 'Directory where per-workspace sqlite-vec stores live.',
    default: 'data/priorart/vectors',
    scope: 'server',
  },
];

export const priorArtConfigDefaults: Record<string, unknown> = {
  usptoOdpApiKey: '',
  usptoOdpBaseUrl: 'https://api.uspto.gov',
  usptoOdpLegacyBaseUrl: 'https://developer.uspto.gov',
  oaUseLegacyHost: true,
  gcpProjectId: '',
  gcpCredentialsPath: '',
  bigqueryPatentsDataset: 'patents-public-data.patents.publications',
  bigqueryBytesBilledCap: '300000000000',
  embeddingModel: 'Xenova/bge-m3',
  embeddingDimension: '1024',
  coverageThreshold: '0.72',
  cpcWhitelist: 'G06F,G06N,G06Q,G06T,G06V,H04L,H04W,H01L,G11C,G05B,H03K,G06K',
  uspcWhitelist: '706,707,708,709,710,711,712,713,714,716,717,718,719,257,326,327,365',
  enableDeepResearchReframe: true,
  deepResearchReframeModel: 'gemini-2.5-pro',
  maxResultsPerSource: '50',
  maxDocumentsToEmbed: '200',
  topK: '20',
  requestTimeoutSeconds: '30',
  workspacePath: 'data/priorart/workspaces',
  vectorStorePath: 'data/priorart/vectors',
};
